validationCommande:
    path:  /api/banque/{id}
    defaults: { _controller: EcommerceBundle:Commandes:validationCommande }
BackCommande:
    path:  /Back/Commandes
    defaults: { _controller: EcommerceBundle:Back:Back }

DelCommande:
    path:  /Back/Commandes/Del/{id}
    defaults: { _controller: EcommerceBundle:Back:Del }
